format = "$directory$git_branch$git_status$fill$cmd_duration\n$character"

[fill]
symbol = " "

[character]
success_symbol = "[>](#d87c4a)"
error_symbol = "[>](#B14242)"
vimcmd_symbol = "[<](#d87c4a)"

[directory]
style = "#d5d5d5"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "#E49A44"
format = "[$symbol$branch]($style) "

[git_status]
style = "#B14242"
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2_000
style = "#d5d5d5"
format = "[$duration]($style)"
show_milliseconds = false

[python]
symbol = ""
style = "#E49A44"

[git_state]
style = "#E49A44"
